version: "3"
services:

  webserver:
    container_name: plone_nginx
    image: nginx:1.25.4
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "${NGINX_HTTP_PORT:-80}:80"

  frontend:
    container_name: plone_frontend
    image: plone/plone-frontend:17.15.3
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend

  backend:
    container_name: plone_backend
    image: plone/plone-backend:6.0
    environment:
      SITE: Plone
      RELSTORAGE_DSN: "dbname=${POSTGRES_DB:-plone} user=${POSTGRES_USER:-plone} host='db' password=${POSTGRES_PASSWORD:-plone}"
    ports:
    - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - db

  db:
    container_name: plone_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-plone}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-plone}
      POSTGRES_DB: ${POSTGRES_DB:-plone}
    volumes:
    - ./volumes/data:/var/lib/postgresql/data
    ports:
    - "${POSTGRES_PORT:-55432}:5432"